#!/bin/sh
# tmux attach directory
# inspired by https://github.com/croaky/dotfiles/commit/df3dd5129bfa941ac0bdf2885da92f822042ee5b

SESSION=$(basename $PWD)

# credit from http://stackoverflow.com/questions/3432536/create-session-if-none-exists
function hassession {
tmux has-session -t $SESSION 2>/dev/null
}

if hassession
then
tmux attach -t $SESSION
else
tmux new-session -s $SESSION
fi

# http://www.119labs.com/blog/2013/01/15/tmux-quick-connect/
